pipeline:
  name: HelmRemoteServiceTest
  identifier: HelmRemoteServiceTest
  projectIdentifier: CSE_Lab_Project
  orgIdentifier: CSE_Labs
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: remoteHelmServiceTest
            gitBranch: austin-test
            serviceInputs:
              serviceDefinition:
                type: NativeHelm
                spec:
                  manifests:
                    - manifest:
                        identifier: nginx
                        type: HelmChart
                        spec:
                          chartVersion: <+input>
          environment:
            environmentRef: csegcpclusternew
            deployToAll: false
            infrastructureDefinitions:
              - identifier: austintestns
          execution:
            steps:
              - step:
                  name: Helm Deployment
                  identifier: helmDeployment
                  type: HelmDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
