pipeline:
  name: GenesisTester
  identifier: GenesisTester
  projectIdentifier: CSE_Lab_Project
  orgIdentifier: CSE_Labs
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        tags: {}
        template:
          templateRef: GenesisDeploy
          versionLabel: "1"
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
              environment:
                environmentRef: <+input>
                infrastructureDefinitions: <+input>
                environmentInputs: <+input>
            variables:
              - name: version_fallback
                type: String
                value: <+input>
              - name: jira_id
                type: String
                value: <+input>
            when:
              condition: <+input>
