pipeline:
  name: gitex-migration-test
  identifier: gitexmigrationtest
  projectIdentifier: CSE_Lab_Project
  orgIdentifier: CSE_Labs
  tags: {}
  stages:
    - stage:
        name: buildMe
        identifier: buildMe
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: csegcpcluster
              namespace: austin-test-ns
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.AT_Docker
                    image: library/nginx
                    shell: Sh
                    command: echo "hello world"
    - stage:
        name: run
        identifier: run
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "hello"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  name: echoNothing
                  identifier: echoNothing
                  template:
                    templateRef: echoNothing
                    versionLabel: "1"
        tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Harness_Labs
        repoName: harness-labs
        build: <+input>
