pipeline:
  name: gitex-migration-test
  identifier: gitexmigrationtest
  projectIdentifier: CSE_Lab_Project
  orgIdentifier: CSE_Labs
  tags: {}
  stages:
    - stage:
        name: run
        identifier: run
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "hello"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  name: echoNothing
                  identifier: echoNothing
                  template:
                    templateRef: echoNothing
                    versionLabel: "1"
              - step:
                  name: echoNothing2
                  identifier: echoNothing2
                  template:
                    templateRef: echoNothing2
                    versionLabel: "1"
        tags: {}
