pipeline:
  name: pipelineChain2-test
  identifier: pipelineChain2test
  projectIdentifier: CSE_Lab_Project
  orgIdentifier: CSE_Labs
  tags: {}
  stages:
    - stage:
        name: echo
        identifier: echo
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "hello world"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
