pipeline:
  name: pipelineTemplateStageOnly
  identifier: pipelineTemplateStageOnly
  projectIdentifier: CSE_Lab_Project
  orgIdentifier: CSE_Labs
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        tags: {}
        template:
          templateRef: account.stageTemplateFromAccount
          templateInputs:
            type: Custom
            variables:
              - name: test
                type: String
                value: <+input>
