pipeline:
  name: pipelineChain1
  identifier: pipelineChain1
  projectIdentifier: CSE_Lab_Project
  orgIdentifier: CSE_Labs
  tags: {}
  stages:
    - stage:
        name: run
        identifier: run
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "hello world"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: test
        identifier: test
        description: ""
        type: Pipeline
        spec:
          org: CSE_Labs
          pipeline: pipelineChain2
          project: CSE_Lab_Project
          inputs:
            identifier: pipelineChain2
            stages:
              - stage:
                  identifier: run
                  type: Custom
                  variables:
                    - name: test
                      type: String
                      value: hello world
