pipeline:
  name: reconcile-template-pipeline
  identifier: reconciletemplatepipeline
  tags: {}
  template:
    templateRef: account.testReconcile
    versionLabel: "1"
    gitBranch: main-reconcile
  projectIdentifier: CSE_Lab_Project
  orgIdentifier: CSE_Labs
