pipeline:
  name: test-push-pipeline
  identifier: testpushpipeline
  projectIdentifier: CSE_Lab_Project
  orgIdentifier: CSE_Labs
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.accountharnesslabs
        repoName: harness-labs
        build: <+input>
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: csegcpcluster
              namespace: austin-test-ns
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: Harness_Labs
                    repoName: harness-labs-cie
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.AT_Docker
                    image: library/nginx
                    shell: Sh
                    command: echo "testing make a afafa"
