apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: diff-demo
  namespace: austin-gitops-ns
spec:
  serviceName: diff-demo
  replicas: 1
  selector:
    matchLabels:
      app: diff-demo
  template:
    metadata:
      labels:
        app: diff-demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.27
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: oci-bv
        volumeMode: Filesystem
