metadata:
  name: "flask-appset"
apiVersion: "argoproj.io/v1alpha1"
kind: "ApplicationSet"
spec:
  template:
    metadata:
      name: "{{appName}}"
      labels:
        harness.io/serviceRef: "{{serviceTag}}"
        harness.io/envRef: "{{envTag}}"
    spec:
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{namespace}}"
      project: "{{project}}"
      source:
        repoURL: "https://github.com/austinthao5/harness-labs.git"
        path: "gitops/flask-app"
        targetRevision: "main"
      syncPolicy:
        automated:
          selfHeal: false
          prune: true
  generators:
  - git:
      repoURL: "https://github.com/austinthao5/harness-labs.git"
      files:
      - path: "gitops-applications/configs/flask-app.yaml"
      revision: "HEAD"
