createNamespace: true
replicas: 1
staticNamespace: austin-test-values-ns
otherValue: <+pipeline.stages.<+stage.identifier>.spec.execution.steps.retrieve_aws_credentials_deploy.output.outputVariables.TF_SERVICE_RUNTIME_ROLE>
