apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk-demo
  labels:
    app: splunk-demo
  namespace: splunk-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splunk-demo
  template:
    metadata:
      labels:
        app: splunk-demo
      annotations:
        redeployCount: "{{ .Values.redployCount }}"
    spec:
      containers:
        - name: flask-container
          image: austinthao/flask-app:v1
          readinessProbe:
            httpGet:
              path: /
              port: 80
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: splunk-demo
  namespace: splunk-demo
spec:
  selector:
    app: splunk-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

  ports:
    - port: 80
      targetPort: 80
