extraDeploy:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: fail-job
      annotations:
        "helm.sh/hook": post-install
    spec:
      template:
        spec:
          containers:
            - name: fail
              image: busybox
              command: ["false"]
          restartPolicy: Never
