extraDeploy:
  - apiVersion: v1
    kind: Service
    metadata:
      name: invalid-service
    spec:
      selector:
        app: nginx
      ports:
        - protocol: TCP
          port: 80
          targetPort: invalid-port  # <-- This causes failure. Should be a number or valid named por
