apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluegreen-example
  labels:
    app: bluegreen-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluegreen-example
  template:
    metadata:
      labels:
        app: bluegreen-example
    spec:
      containers:
        - name: bluegreen-example
          image: hashicorp/http-echo
          args:
            - "-text=$(COLOR)"
          env:
            - name: COLOR
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['harness.io/color']
          ports:
            - containerPort: 5678
