# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-{{ .Values.color }}
  labels:
    app: my-app
    environment: {{ .Values.color }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      environment: {{ .Values.color }}
  template:
    metadata:
      labels:
        app: my-app
        environment: {{ .Values.color }}
    spec:
      containers:
        - name: my-app-container
          image: hashicorp/http-echo
          args:
            - "-text=$(COLOR)"
          env:
            - name: COLOR
              valueFrom:
                configMapKeyRef:
                  name: app-color-{{ .Values.color }}
                  key: COLOR
          ports:
            - containerPort: 5678
