# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bluegreen-example-service
spec:
  selector:
    app: bluegreen-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
  type: ClusterIP
