apiVersion: v1
kind: Service
metadata:
  name: bluegreen-example-service
spec:
  selector:
    app: bluegreen-example
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5678
  type: LoadBalancer
