apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-example
  labels:
    app: canary-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-example
  template:
    metadata:
      labels:
        app: canary-example
    spec:
      containers:
        - name: canary-example
          image: hashicorp/http-echo
          args:
            - "-text=Harness Canary Deploying: $(TRACK)"
          env:
            - name: TRACK
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['harness.io/track']
          ports:
            - containerPort: 5678
