apiVersion: v1
kind: Service
metadata:
  name: canary-example-service
spec:
  selector:
    app: canary-example
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5678
  type: LoadBalancer
