# harness.io/skip-file-for-deploy
{{- if .Values.createNamespace}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.staticNamespace}}-1
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.staticNamespace}}-{{.Values.testVar}}-2
{{- end}}
