apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: another-fake-configmap
data:
  c360.case-management.case-error-topic-name: "case-error-topic-qa"
  c360.case-management.case-request-topic-name: "private.adc.self_service.case_request.qa"
  c360.case-management.config.profile-activity-max-attempts: "4"
  c360.case-management.config.sendgrid-confirmation-max-attempts: '2'
  some-key: "some-value"
    
