apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "guestbook"
  namespace: "austin-argocd"
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "austin-argocd"
  project: "2d97e61f"
  source:
    repoURL: "https://github.com/austinthao5/harness-labs.git"
    path: "gitops/guestbook"
    targetRevision: "main"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
