common: &common_values
  envTag: "gitopsdemo"
  namespace: "austin-gitops-demo"
  project: "2d97e61f"

deployment:
  <<: *common_values
  appName: "flask-app"
  serviceTag: "flaskapp"
  abc: "456"
  harnessPR: "PipelineExecution35"
