rollout-CanaryWorker.image.tag: 6IZ6DArVS4O8tH1JhbM0Gg
envTag: gitopsdemo
appName: flask-app
serviceTag: flaskapp
namespace: austin-test-ns2
project: 3164c471
rollout-Canary.image.tag: 6IZ6DArVS4O8tH1JhbM0Gg
version: 6IZ6DArVS4O8tH1JhbM0Gg
