abc: "456"
envTag: "gitopsdemo"
rollout-CanaryWorker:
  image:
    tag: "56FC3CQWR7efg8ZpyKXFrA"
appName: "flask-app"
serviceTag: "flaskapp"
namespace: "austin-test-ns2"
project: "3164c471"
rollout-Canary:
  image:
    tag: "56FC3CQWR7efg8ZpyKXFrA"
harnessPR: "PipelineExecution35"
version: "56FC3CQWR7efg8ZpyKXFrA"
