apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-creator
  namespace: austin-prod1-agent
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-creator-binding
  namespace: austin-prod1-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configmap-creator
subjects:
  - kind: ServiceAccount
    name: default
    namespace: austin-prod1-agent
