---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helloworld-config
data:
  MESSAGE: "Hello from Knative ConfigMap!"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
spec:
  template:
    spec:
      containers:
      - image: gcr.io/knative-samples/helloworld-go
        envFrom:
        - configMapRef:
            name: helloworld-config
