apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: demo-cloudrun
spec:
  template:
    spec:
      containers:
        - image: austinthao/flask-app:v2
          ports:
            - containerPort: 80
